apiVersion: v2
description: Deploy Kong Ingress Controller and Kong Gateway
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
  - name: team-k8s-bot
    email: team-k8s@konghq.com
name: ingress
sources:
  - https://github.com/manjunathkp-numo/charts/tree/main/charts/ingress   
